# accelerate launch --main_process_port 29509 train.py --config 'configs/ae_find_schedule.yaml'
accelerate launch --main_process_port 29508 gpt_train.py --config 'configs/a800_GPT.yaml'
# accelerate launch --main_process_port 29508 gpt_train.py --config 'configs/gpt_total.yaml'
# accelerate launch --main_process_port 29507 train_ae_total.py --config 'configs/a800_AE.yaml'
# accelerate launch --main_process_port 29507 train_ae_total.py --config 'configs/g2_AE.yaml'