autoencoder:
  vae_dim: &vae_dim 256
  # num_latents: &num_latents 1024
  num_latents: &num_latents 512
  binary_dim: &binary_dim 16
  # binary_dim: &binary_dim 64
  # binary_dim: &binary_dim 36
  outer_ckpt:
  inner_ckpt:

  encoder_1d:
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    output_dim: *binary_dim
  decoder_1d:
    block_size: 16
    binary_mode: true
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    input_dim: *binary_dim
    latents_mask_schedule: '1_to_16_512'

hybrid_loss:
  disc_start: 10000
  disc_weight: 0.05

train:
  warm_up_step: 0
  resume_path: 'experiment/2_to_32/EMA-ae_total-30k'
  skipped_keys: ['encoder_1d.output.weight', 'encoder_1d.output.bias', 'decoder_1d.input.weight', 'decoder_1d.latents_mask']
  loss_resume_path: 'experiment/2_to_32/Loss-ae_total-30k'
  global_step: 0
  exp_name: &exp_name 'tokenizer'
  wandb_proj: *exp_name
  output_dir: 'AE_new-1_to_16-512-165_245'
  logging_dir: 'logs'
  mixed_precision: 'bf16'
  gradient_accumulation_steps: 2
  report_to: 'no'
  num_iters: 20000
  save_every: 5000
  hp_matryoshka: 1

data:
  # path: '/root/data/imagenet/imagenet-train-{000000..001281}.tar'
  path: '/data/Largedata/ImageNet_wds/imagenet-train-{000165..000245}.tar'
  # path: '/data/Largedata/ImageNet_wds/imagenet-train-{000000..001281}.tar'
  batch_size: 7