autoencoder:
  vae_dim: &vae_dim 256
  num_latents: &num_latents 1024
  # num_latents: &num_latents 512
  binary_dim: &binary_dim 32
  # binary_dim: &binary_dim 64
  # binary_dim: &binary_dim 36
  outer_ckpt:
  inner_ckpt:

  encoder_1d:
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    output_dim: *binary_dim
  decoder_1d:
    binary_mode: true
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    input_dim: *binary_dim
    latents_mask_schedule: 'linear_1024_32'
    # latents_mask_schedule: 'linear_1024_36'

hybrid_loss:
  disc_start: 1000
  disc_weight: 0.03

train:
  resume_path: '/root/codebase/glowing-spoon/experiment/ae_total/1024x32_hp5_cont/EMA-ae_total-10k'
  # skipped_keys: []
  skipped_keys:
  loss_resume_path: '/root/codebase/glowing-spoon/experiment/ae_total/1024x32_hp5_cont/EMA-ae_total-10k/Loss-ae_total-10k'
  global_step: 
  exp_name: &exp_name 'ae_total'
  wandb_proj: *exp_name
  output_dir: 'linear_1024_32_do'
  logging_dir: 'logs'
  mixed_precision: 'bf16'
  gradient_accumulation_steps: 1
  report_to: 'no'
  num_iters: 100000
  save_every: 1000
  hp_matryoshka: 5

data:
  path: '/root/data/imagenet/imagenet-train-{000000..001281}.tar'
  batch_size: 20