autoencoder:
  vae_dim: &vae_dim 16
  num_latents: &num_latents 512
  binary_dim: &binary_dim 24
  outer_ckpt: 'pretrained_models/vae/kl16.ckpt'
  inner_ckpt: 'experiment/AE_512_linear_24/AE-distill_MAR_VAE-2k'

  encoder_1d:
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    output_dim: *binary_dim
  decoder_1d:
    binary_mode: true
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    input_dim: *binary_dim
    latents_mask_schedule: 'linear_24'

hybrid_loss:
  disc_start: 1
  disc_weight: 0.05

train:
  resume_path:
  skipped_keys:
  global_step:
  exp_name: &exp_name 'ae_total'
  wandb_proj: *exp_name
  # output_dir: *exp_name
  output_dir: 'ae_total/512_24'
  logging_dir: 'logs'
  mixed_precision: 'bf16'
  gradient_accumulation_steps: 2
  report_to: 'wandb'
  num_iters: 20000
  # val_every: 50
  save_every: 2000

data:
  path: '/data/Largedata/ImageNet_wds/imagenet-train-{000000..001281}.tar'
  batch_size: 7