autoencoder:
  vae_dim: &vae_dim 256
  num_latents: &num_latents 512
  binary_dim: &binary_dim 64
  outer_ckpt:
  inner_ckpt:

  encoder_1d:
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    output_dim: *binary_dim
  decoder_1d:
    binary_mode: true
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    input_dim: *binary_dim
    latents_mask_schedule: 'linear_64'

hybrid_loss:
  disc_start: 1
  disc_weight: 0.03

train:
  resume_path: './ckpts/AE-ae_total-a800-ckpt'
  skipped_keys: 
  loss_resume_path: './ckpts/Loss-ae_total-a800-ckpt'
  global_step:
  exp_name: &exp_name 'ae_total'
  wandb_proj: *exp_name
  output_dir: 'ae_total/linear_64_z256'
  logging_dir: 'logs'
  mixed_precision: 'bf16'
  gradient_accumulation_steps: 4
  report_to: 'wandb'
  num_iters: 100000
  save_every: 2000
  hp_matryoshka: 0.05

data:
  path: './datasets/imagenet/imagenet-train-{000000..001281}.tar'
  batch_size: 20