autoencoder:
  vae_dim: &vae_dim 16
  num_latents: &num_latents 512
  binary_dim: &binary_dim 32
  outer_ckpt:
  inner_ckpt:

  encoder_1d:
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    output_dim: *binary_dim
  decoder_1d:
    binary_mode: true
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    input_dim: *binary_dim
    latents_mask_schedule: 'step_linear_32'

hybrid_loss:
  disc_start: 1
  disc_weight: 0.05

train:
  resume_path: '/data/experiment/ae_total/step_linear_32/AE-ae_total-26k'
  skipped_keys:
  loss_resume_path: '/data/experiment/ae_total/step_linear_32/Loss-ae_total-26k'
  # resume_path: 'experiment/ae_total/512_24/AE-ae_total-10k'
  # skipped_keys: ['encoder_1d.output.weight', 'encoder_1d.output.bias', 'encoder_1d.output.weight', encoder_1d.output.bias', 'decoder_1d.latents_mask', 'decoder_1d.input.weight', 'decoder_1d.input.bias']
  global_step: 26001
  exp_name: &exp_name 'ae_total'
  wandb_proj: *exp_name
  # output_dir: *exp_name
  output_dir: 'ae_total/step_linear_32'
  logging_dir: 'logs'
  mixed_precision: 'bf16'
  gradient_accumulation_steps: 2
  report_to: 'wandb'
  num_iters: 100000
  # val_every: 50
  save_every: 5000
  hp_matryoshka: 0.1

data:
  path: '/data/imagenet/imagenet-train-{000000..001281}.tar'
  batch_size: 20