residual: &residual false
autoencoder:
  pretrained_ckpt_path: 'experiment/AE_512_linear_24/AE-distill_MAR_VAE-2k'
  binary_dim: &binary_dim 24
  # pretrained_ckpt_path: 'experiment/matryoshka_casual_latents_incre/AE-distill_MAR_VAE-5k'
  # binary_dim: &binary_dim 16
  vae_dim: &vae_dim 16
  num_latents: &num_latents 512
  matryoshka: true
  encoder:
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    output_dim: *binary_dim
  
  decoder_matryoshka:
    binary_mode: true
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    input_dim: *binary_dim
    # latents_mask_schedule: 'linear_16'
    latents_mask_schedule: 'linear_24'
    # latents_mask_schedule: 'exp_32'
    # latents_mask_schedule: 'exp_48'
    # latents_mask_schedule: 'flat_exp_32'

gpt:
  independent_projection: false
  block_size: 16
  seq_len: 512
  dim: 1024
  n_layer: 16
  n_head: 16
  norm_eps: 1e-5
  resid_dropout_p: 0.0
  token_dropout_p: 0.0
  attn_dropout_p: 0.0
  drop_path_rate: 0.0
  ffn_dropout_p: 0.0
  num_classes: 1000
  class_dropout_prob: 0.1
  cls_token_num: 1
  input_dim: *binary_dim
  multiple_of: 256
  n_kv_head:
  ffn_dim_multiplier:

train:
  num_pred_bits:
  resume_path: 'experiment/gpt_causal_latents_incre/linear_24/GPT-gpt_newtok-25k'
  skipped_keys:
  # skipped_keys: ['tok_eb.weight', 'tok_eb.bias', 'output.weight', 'output.bias']
  global_step: 25001
  exp_name: &exp_name 'gpt_newtok'
  wandb_proj: *exp_name
  # output_dir: *exp_name
  output_dir: 'gpt_causal_latents_incre/linear_24'
  logging_dir: 'logs'
  mixed_precision: 'bf16'
  gradient_accumulation_steps: 1
  report_to: 'wandb'
  num_iters: 50000
  save_every: 5000

data:
  path: '/data/Largedata/ImageNet_wds/imagenet-train-{001250..001281}.tar'
  batch_size: 30 # to modify

