total: true
autoencoder:
  matryoshka: true
  pretrained_ckpt_path: 'pretrained_models/aliyun/EMA_2k'
  # pretrained_ckpt_path: 'pretrained_models/a800/AE-ae_total-a800-ckpt'
  # pretrained_ckpt_path: 'experiment/ae_total/512_24/AE-ae_total-10k'
  # pretrained_ckpt_path: 'experiment/ae_total/512_step_linear_32/AE-ae_total-5k'
  vae_dim: &vae_dim 256
  num_latents: &num_latents 512
  binary_dim: &binary_dim 64
  # binary_dim: &binary_dim 32
  outer_ckpt:
  inner_ckpt:

  encoder_1d:
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    output_dim: *binary_dim

  decoder_1d:
    binary_mode: true
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    input_dim: *binary_dim
    # latents_mask_schedule: 'linear_24'
    # latents_mask_schedule: 'step_linear_32'
    latents_mask_schedule: 'linear_64'

gpt:
  # block_size:
  # block_size: 16
  independent_projection: true
  block_size: 8
  num_classes: 1000
  dim: 1024
  n_layer: 16
  n_head: 16
  seq_len: *num_latents
  norm_eps: 1e-5
  resid_dropout_p: 0.0
  token_dropout_p: 0.0
  attn_dropout_p: 0.0
  drop_path_rate: 0.0
  ffn_dropout_p: 0.0
  
  class_dropout_prob: 0.1
  cls_token_num: 1
  input_dim: *binary_dim
  multiple_of: 256
  n_kv_head:
  ffn_dim_multiplier:

train:
  num_pred_bits:
  resume_path: 'experiment/gpt_causal_latents_incre/block_linear_64/GPT-gpt_newtok-25k'
  skipped_keys:
  # skipped_keys: ['tok_eb.weight', 'tok_eb.bias', 'output.weight', 'output.bias']
  global_step: 25001
  exp_name: &exp_name 'gpt_newtok'
  wandb_proj: *exp_name
  # output_dir: *exp_name
  output_dir: 'gpt_causal_latents_incre/indep_proj'
  logging_dir: 'logs'
  mixed_precision: 'bf16'
  gradient_accumulation_steps: 1
  report_to: 'no'
  num_iters: 50000
  save_every: 5000

data:
  path: '/data/Largedata/ImageNet_wds/imagenet-train-{000000..001281}.tar'
  batch_size: 10 # to modify

