total: true
autoencoder:
  matryoshka: true
  pretrained_ckpt_path: '/checkpoint/data_gen_exp/pretrained_ckpts/ema_6k_new'
  vae_dim: &vae_dim 256
  num_latents: &num_latents 1024
  binary_dim: &binary_dim 32
  outer_ckpt:
  inner_ckpt:

  encoder_1d:
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    output_dim: *binary_dim

  decoder_1d:
    binary_mode: true
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    input_dim: *binary_dim
    latents_mask_schedule: 'linear_1024_32'

gpt:
  independent_projection: false
  block_size: 16
  num_classes: 1000
  dim: 2048
  n_layer: 32
  n_head: 32
  seq_len: *num_latents
  norm_eps: 1e-5
  resid_dropout_p: 0.0
  token_dropout_p: 0.0
  attn_dropout_p: 0.0
  drop_path_rate: 0.0
  ffn_dropout_p: 0.0
  
  class_dropout_prob: 0.1
  cls_token_num: 1
  input_dim: *binary_dim
  multiple_of: 256
  n_kv_head:
  ffn_dim_multiplier:

train:
  flip_prob: 0.048 # TBD
  flip_decay: 0.98 # TBD
  flip_decay_every: 5000 # TBD
  warm_up_step: 0
  num_pred_bits:
  resume_path: /data-fast/Xlarge_v1_1.6B/GPT-GPT_H100-20k
  skipped_keys:
  global_step: 19999
  exp_name: &exp_name 'GPT_H100'
  wandb_proj: *exp_name
  output_dir: '/data-fast/Xlarge_1.6B'
  logging_dir: 'logs'
  mixed_precision: 'bf16'
  gradient_accumulation_steps: 8 # TBD
  report_to: 'wandb'
  num_iters: 1280000 # TBD
  save_every: 10000 # TBD
  val_every: 40000 # TBD
  ori_path: '/data-fast/eval_images/assets/ori' # where the original images are stored

data:
  path: '/checkpoint/data_gen_exp/datasets/imagenet/imagenet-train-{000000..001281}.tar'
  batch_size: 2 # TBD