autoencoder:
  binary_dim: &binary_dim 16
  vae_dim: &vae_dim 16
  num_latents: &num_latents 256
  encoder:
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    output_dim: *binary_dim

  decoder:
    binary_mode: false
    vae_dim: *vae_dim
    embed_dim: 512
    num_layers: 8
    num_latents: *num_latents
    num_heads: 8
    input_dim: *binary_dim
    recon_levels: [1, 2, 3, 4, 5, 6, 8, 10, 13, 16] # the same as VAR

train:
  resume_path: 'experiment/distill_MAR_VAE/AE-distill_MAR_VAE-6k'
  global_step: 6001
  exp_name: &exp_name 'distill_MAR_VAE'
  wandb_proj: *exp_name
  # output_dir: *exp_name
  output_dir: 'distill_continuous'
  logging_dir: 'logs'
  mixed_precision: 'bf16'
  gradient_accumulation_steps: 1
  report_to: 'wandb'
  num_iters: 10000
  # val_every: 10
  save_every: 1000

data:
  path: '/data/Largedata/ImageNet_wds/imagenet-train-{000000..001281}.tar'
  batch_size: 70 # to modify